#端口号
server:
  port: 15213
spring:
  profiles:
    active: dev #设为开发环境
  main:
    allow-circular-references: true

  datasource:
    #设置数据库连接
    url: jdbc:mysql://localhost:3306/employment_system
    username: root
    password: 102030aoboco
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet: #设置文件上传大小限制
    multipart:
      max-file-size: 4000MB
      max-request-size: 6000MB
  data:
    redis:
      port: 6379
      host: localhost
      lettuce:
        pool:
          max-wait: 100
          max-active: 8
          max-idle: 8
          min-idle: 0
      password:

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.glimmer.entity
  configuration:
    log-impl: org.apache.ibatis.logging.commons.JakartaCommonsLoggingImpl
    map-underscore-to-camel-case: true #开启驼峰命名
