version: '3.8'
services:
  app:
    build: .
    ports:
      - 15213:15213
    depends_on:
      - mysql
      - redis
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    restart: always
    ports:
      - 3306:3306
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 200296lpl
      MYSQL_DATABASE: employment_system
      MYSQL_USER: lpl
      MYSQL_PASSWORD: 200296lpl.
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    restart: always
volumes:
  mysql-data: